# workflow 名称，可以自定义
name: Deploy GitHub Pages

# 触发条件：在代码 push 到 master 分支后，自动执行该 workflow
on:
  push:
    branches:
      - main

permissions:
  contents: write
# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu，也可以自定义版本
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true
          
      # 设置 Node.js 版本
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "21.7.1"
          cache: npm
      
      - name: 安装依赖
        run: npm ci    

      # 生成静态文件
      - name: Build
        run:  npm run build

      # 部署到 GitHub Pages
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # ACCESS_TOKEN 是创建的 Secret 名称，替换为你自己创建的名称
        with:
          target-branch: gh-pages # 部署到 gh-pages 分支，master 分支存放的是项目源码，而 gh-pages 分支则用来存放生成的静态文件
          build_dir: .vuepress/dist # vuepress 生成的静态文件存放的地方
